apiVersion: v1
kind: Service
metadata:
  name: cqrs-service
  namespace: k8s-demo-guilherme
spec:
  type: NodePort
  selector:
    app: cqrs
  ports:
  - port: 80
    name: swagger
  - port: 27017
    name: mongo